# Generated by Django 4.1.7 on 2023-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=10)),
                ('preco', models.CharField(max_length=10)),
                ('qtd', models.CharField(max_length=10)),
            ],
        ),
    ]
