# Generated by Django 4.1.7 on 2023-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='preco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='qtd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
